version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - .:/go/src/github.com/TailorDev/crick/api
    environment:
      CRICK_DSN: postgres://crick:crickIsChic@db:5432/crick
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: crick
      POSTGRES_USER: crick
      POSTGRES_PASSWORD: crickIsChic
